evercam-dashboard/config/routes.rb
Rails.application.routes.draw do
  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v2/payments' => 'payments#new', as: :new_checkout
  post '/v2/payments' => 'payments#create', as: :new_charge

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v2/cameras'), as: :root
  get '/v2/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras' => 'cameras#index'  # temporary route
  get '/v2/cameras/new' => 'cameras#new', as: :cameras_new
  post '/v2/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v2/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id' => 'cameras#single' # temporary route
  get '/v2/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v2/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v2/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v2/cameras/:id/archives/:archive_id/play' => 'pages#play', as: :play_clip
  get '/v2/cameras/:id/share/request' => 'pages#revoke_request'
  get '/v2/swagger' => "pages#swagger"
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v2/cameras/:id/*subpath' => 'cameras#single'

  get '/v2/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/timelapses' => 'timelapses#index', as: :timelapses_index

  get '/v2/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v2/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v2/users/signup' => 'users#new', as: :signup
  get '/v1/users/signup' => 'users#new' # temporary route
  post '/v2/users/signup' => 'users#create'
  post '/v1/users/signup' => 'users#create' # temporary route
  get '/v2/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v2/users/password-reset' => 'users#password_reset_request'
  get '/v2/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v2/users/password-new' => 'users#password_update'
  get '/confirm' => 'users#confirm'
  get '/v2/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  get '/v2/users/signout' => 'sessions#destroy'
  get '/v1/users/signout' => 'sessions#destroy' # temporary route
  delete '/v2/users/signout' => 'sessions#destroy', as: :signout

  # Removed username from url
  get '/v2/users/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/v2/users/account' => 'users#settings', as: :user_settings
  get '/v2/users/settings', to: redirect("/v2/users/account")
  delete '/v2/users/account' => 'users#delete'
  post '/v2/users/account' => 'users#settings_update'
  put '/v2/users/password/change' => 'users#change_password', as: :user_change_password
  # Removed username from url

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'

  namespace :widgets do
    resources :widget_cameras_add, path: :widget_cameras_add
    get '/cameras/add' => 'widget_cameras_add#widget_add_camera', as: :widget_camera_add
    get '/cameras/public/add' => 'widget_cameras_add#add_public_camera'
    get '/add.camera' => 'widget_cameras_add#add_camera'

    resources :widget_timelapse, path: :widget_timelapse
    get '/timelapse-widget' => 'widget_timelapse#timelapse_js'
  end

  get '/test' => 'cameras#test', as: :test
  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

evercam-dashboard/app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :authenticate_user!, :except=>[:single, :test]
  include SessionsHelper
  include ApplicationHelper
  include CamerasHelper
  require 'socket'
  require 'timeout'

  def index
    @cameras = load_user_cameras(true, false)
    @camera_count = @cameras.count
    @show_alert_message = false
    @required_licences = 0
  end

  def new
    @cameras = load_user_cameras(true, false)
    @user = (flash[:user] || {})
    @ip = request.remote_ip
    if @user == {} && params[:id]
      camera = get_evercam_api.get_camera(params[:id], false)
      @user['camera-id'] = camera['id']
      @user['camera-username'] = camera['cam_username']
      @user['camera-password'] = camera['cam_password']
      @user['camera-url'] = camera.deep_fetch('external', 'host')
      @user['port'] = camera.deep_fetch('external', 'http', 'port') {}
      @user['ext-rtsp-port'] = camera.deep_fetch('external', 'rtsp', 'port') {}
      @user['camera-vendor'] = camera['vendor_id']
      @user['camera-model'] = camera['model_id']
      @user['local-ip'] = camera.deep_fetch('internal', 'host') {}
      @user['local-http'] = camera.deep_fetch('internal', 'http', 'port') {}
      @user['local-rtsp'] = camera.deep_fetch('internal', 'rtsp', 'port') {}
      if camera.deep_fetch('location') { '' }
        @user['camera-lat'] = camera.deep_fetch('location', 'lat') {}
        @user['camera-lng'] = camera.deep_fetch('location', 'lng') {}
      end
      if camera.deep_fetch('external', 'http', 'jpg') { '' }
        @user['snapshot'] = camera.deep_fetch('external', 'http', 'jpg') { '' }.
          sub("http://#{camera.deep_fetch('external', 'host') { '' }}", '').
          sub(":#{camera.deep_fetch('external', 'http', 'port') { '' }}", '')
      end
      if camera.deep_fetch('external', 'rtsp', 'h264') { '' }
        @user['rtsp'] = camera.deep_fetch('external', 'rtsp', 'h264') { '' }.
          sub("rtsp://#{camera.deep_fetch('external', 'host') { '' }}", '').
          sub(":#{camera.deep_fetch('external', 'rtsp', 'port') { '' }}", '')
      end
    end
  end

  def create
    begin
      raise "No camera name specified in request." if params['camera-name'].blank?

      body = {external_host: params['camera-url'], jpg_url: params['snapshot']}
      body[:cam_username] = params['camera-username'] unless params['camera-username'].blank?
      body[:cam_password] = params['camera-password'] unless params['camera-password'].blank?
      body[:vendor] = params['camera-vendor'] unless params['camera-vendor'].blank?
      body[:model] = params["camera-model"] unless params["camera-model"].blank? if body[:vendor]
      body[:internal_http_port] = params['local-http'] unless params['local-http'].blank?
      body[:external_http_port] = params['port'] unless params['port'].blank?
      body[:internal_rtsp_port] = params['local-rtsp'] unless params['local-rtsp'].blank?
      body[:external_rtsp_port] = params['ext-rtsp-port'] unless params['ext-rtsp-port'].blank?
      body[:internal_host] = params['local-ip'] unless params['local-ip'].blank?
      body[:location_lat] = params['camera-lat'] unless params['camera-lat'].blank?
      body[:location_lng] = params['camera-lng'] unless params['camera-lng'].blank?
      body[:is_online] = true
      tzc = TZInfo::Country.get(@current_user.country.iso3166_a2.upcase)
      timezone = Timezone::Zone.new zone:tzc.zone_names.first
      body[:timezone] = timezone.name[:zone]
      api = get_evercam_api
      new_camera = api.create_camera(
        params['camera-name'],
        false,
        body
      )
      redirect_to cameras_single_path(new_camera["id"])
    rescue => error
      flash[:user] = {
        'camera-name' => params['camera-name'],
        'camera-username' => params['camera-username'],
        'camera-password' => params['camera-password'],
        'camera-url' => params['camera-url'],
        'port' => params['port'],
        'ext-rtsp-port' => params['ext-rtsp-port'],
        'snapshot' => params['snapshot'],
        'camera-vendor' => params['camera-vendor'],
        'camera-model' => params['camera-model'],
        'local-ip' => params['local-ip'],
        'local-http' => params['local-http'],
        'local-rtsp' => params['local-rtsp']
      }
      if error.kind_of?(Evercam::EvercamError)
        response = instance_eval{(error.message).first}
        flash[:message] = t("errors.#{error.code}") unless error.code.nil?
        assess_field_errors(response)
      else
        flash[:message] = "An error occurred creating your account. Please check "\
                          "the details and try again. If the problem persists, "\
                          "contact support."
      end
      Rails.logger.error "Exception caught in create camera request.\nCause: #{error}\n" +
          error.backtrace.join("\n")
      if params["add-camera"].present? && params["add-camera"].eql?("test")
        return redirect_to cameras_new_test_path
      else
        return redirect_to cameras_new_path
      end
    end
  end

  def update
    begin
      settings = {
        :name => params['camera_name'],
        :external_host => params['camera_url'],
        :timezone => params['camera_timezone'].blank? ? 'Europe/Dublin' : ActiveSupport::TimeZone.new(params['camera_timezone']).tzinfo.name,
        :internal_host => params['local-ip'],
        :external_http_port => params['port'],
        :internal_http_port => params['local-http'],
        :external_rtsp_port => params['ext_rtsp_port'],
        :nvr_http_port => params["nvr_port"],
        :internal_rtsp_port => params['local_rtsp'],
        :jpg_url => params['snapshot'],
        :h264_url => params['rtsp'],
        :vendor => params['camera_vendor'],
        :model => params['camera_vendor'].blank? ? '' : params['camera_model'],
        :location_lat => params['cameraLat'],
        :location_lng => params['cameraLng'],
        :cam_username => params['camera_username'],
        :cam_password => params['camera_password']
      }
      get_evercam_api.update_camera(params['id'], settings)
      camera = get_evercam_api.get_camera(params["id"], false)
      result = {success: true, camera: camera}
    rescue => error
      Rails.logger.error "Exception caught updating camera details.\nCause: #{error}\n" +
          error.backtrace.join("\n")
      result = {success: false, message: error.message}
    end
    render json: result
  end

  def delete
    begin
      result = {success: true}
      api = get_evercam_api
      if [true, "true"].include?(params[:share])
        api.delete_camera_share(params[:id], current_user.email)
      else
        if params[:camera_specified_id] && params[:camera_specified_id] == params[:id]
          api.delete_camera(params[:id])
        else
          result = {success: false, message: "Invalid camera id specified."}
        end
      end
    rescue => error
      Rails.logger.error "Exception caught deleting camera.\nCause: #{error}\n" +
          error.backtrace.join("\n")
      message = "An error occurred deleting your camera. Please try again "\
                      "and, if the problem persists, contact support."
      result = {success: false, message: message}
    end
    render json: result
  end

  def single
    begin
      if params[:api_id] and params[:api_key]
        authenticate_user!
      end
      @archive_view = false
      api = get_evercam_api
      if @current_user
        @cameras = load_user_cameras(true, false)
        @has_shared = false
        @cameras.map do |c|
          if c['id'].eql?(params[:id])
            @camera = c
            @has_shared = true if @camera['owner'] != current_user.username
            break
          end
        end
        @is_owner = @camera['owner'] == current_user[:username]? true : false
        @user_time = Time.new.in_time_zone(@camera['timezone'])
        @selected_date = @user_time.strftime("%m/%d/%Y")
        @current_time = @user_time.strftime("%H")
        @share = nil
        @owner = nil
        unless @is_owner
          return redirect_to cameras_not_found_path if !@has_shared && !@camera['is_public']
          @owner = User.by_login(@camera['owner'])
        else
          @owner = current_user
        end
      end

      params_subpath = params.fetch('subpath', '')
      tab_name = params_subpath.split('/').first
      archive_id = params_subpath.split('/').last
      if @current_user.nil? && !tab_name.eql?(archive_id)
        @archive_view = true
        @archive = api.get_archive(params[:id], archive_id)
        @camera_id = @archive['camera_id']
        @archive_id = @archive['id']
        @archive_type = "clip"
        if @archive['type'].eql?("compare")
          @archive_type = "compare"
        end
      else
        @camera = api.get_camera(params[:id], true) if @camera.nil?
        @camera['is_online'] = false if @camera['is_online'].blank?
        @has_edit_rights = @camera["rights"].split(",").include?("edit") if @camera["rights"]
        time = ActiveSupport::TimeZone.new(@camera['timezone'])
        @camera['timezone'] = 'Etc/UTC' unless time.utc_offset % 3600 == 0
        time_zone = TZInfo::Timezone.get(@camera['timezone'])
        current = time_zone.current_period
        @offset = current.utc_offset + current.std_offset
      end

      @page = (params[:page].to_i - 1) || 0
      @types = ['accessed', 'viewed', 'edited', 'captured',
        'shared', 'stopped sharing', 'online', 'offline',
        'cloud recordings updated', 'cloud recordings created',
        'archive created', 'archive deleted']

      @camera_shares = nil
      @share_requests = nil
      @cloud_recording = @camera["cloud_recordings"] if @has_edit_rights
      @timelapse_recording = @camera["timelapse_recordings"] if @has_edit_rights
      @timelapse_recording = get_default_settings if @timelapse_recording.nil?
      @cr_status = nil
      if @cloud_recording.nil?
        @cr_status = true

evercam-dashboard/app/helpers/cameras_helper.rb
module CamerasHelper
  def preview(camera, _refresh = false)
    thumbnail = thumbnail_url(camera)
    image_tag(thumbnail, class: "camera-thumbnail", alt: "camera-thumbnail", "data-proxy": thumbnail)
  end

  def thumbnail_url(camera)
    if camera['is_public']
      "#{EVERCAM_MEDIA_API}cameras/#{camera['id']}/thumbnail"
    else
      if params.has_key?(:api_id) and params.has_key?(:api_key)
        "#{EVERCAM_MEDIA_API}cameras/#{camera['id']}/thumbnail?api_id=#{params[:api_id]}&api_key=#{params[:api_key]}"
      else
        "#{EVERCAM_MEDIA_API}cameras/#{camera['id']}/thumbnail?api_id=#{current_user.api_id}&api_key=#{current_user.api_key}"
      end
    end
  end
end

evercam-dashboard/app/views/cameras/new.html.erb
<%= content_for(:title, "Evercam: Add Camera") %>
<div id="add-ip" class="add-ip" />
<div class="page-content-wrapper">
  <div class="page-content">
    <div class="tabbable tabbable-custom">
      <div class="center-tabs">
        <ul class="nav nav-tabs add-camera-page">
          <li class="active">
            <a href="#tab_1_1" data-toggle="tab">
              Add IP Camera </a>
          </li>
        </ul>
      </div>
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1_1">
          <%= form_tag(cameras_new_path, method: 'post', id: 'create-a-camera', class: 'has-validation-callback', autocomplete: 'off', role: 'form') do %>
          <% field_errors = (flash[:field_errors] || {}) %>
          <!-- Workaround for Chrome autofill entering camera user & pass. (autocomplete="off" is no longer obeyed) -->
          <input style="display:none" type="text" name="fakeusernameremembered"/>
          <input style="display:none" type="password" name="fakepasswordremembered"/>
          <%= hidden_field_tag('camera-lat', @user['camera-lat']) %>
          <%= hidden_field_tag('camera-lng', @user['camera-lng']) %>

          <div class="col-sm-8 padding-left-0">
            <div class="row">
              <div class='col-sm-12 copy-from-section margin-bottom-20'>
                <div class="<%= field_errors["vendor"] ? ' has-error' : '' %> col-sm-12 col-md-12">
                  <div id="copy-from" class="col-md-12 col-sm-12 padding-left-0 copy-from">
                    <div class="input-group float-left checkbox margin-right-10">
                      <input id="type-all" name="type" class="" type="checkbox" value="" /> <label class="type-label copy-from-text" for="type-all">Copy settings from existing camera</label>
                    </div>
                    <div class="copy-from-camera form-group float-left">
                      <div class="copy-from">
                        <ul class="nav add-camera-page">
                          <li id="clone-camera-list" class="pull-left">
                            <a class="cameras-dropdown-toggle" data-toggle="dropdown" aria-expanded= "true">
                              <% if params[:id].present? %><%=params[:id] %><% else %>Select Camera<% end %><i class="fa fa-chevron-down fa-copy-from" aria-hidden="true"></i>
                              <i class="fa fa-chevron-up fa-copy-from" aria-hidden="true"></i>
                            </a>
                            <ul class="dropdown-menu scroll-menu" role="menu">
                              <% @cameras.each do |camera| %>
                              <% if camera["rights"].split(",").include?("edit") %>
                                <li class="sub-menu-item <%= is_active?("/cameras/#{camera['id']}") %> <% unless camera['is_online'] %>sidebar-offline<% end %>">
                                <%= image_tag("#{EVERCAM_MEDIA_API}cameras/#{camera['id']}/thumbnail?api_id=#{current_user.api_id}&api_key=#{current_user.api_key}", :class => 'thumbnail-img') %>
                                <%= link_to camera['name'], cameras_clone_path(camera['id']) %>
                              </li>
                              <% end %>
                              <% end %>
                            </ul>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div id="camera-friendly-name" class='col-sm-12 margin-top-20'>
                <div class="col-sm-4 col-md-4 <%= field_errors["name"] ? ' has-error' : '' %>">
                  <div class='form-group'>
                    <i class="far fa-question-circle help-icon camera-name-help-icon" aria-hidden="true" title="To identify your camera in the dashboard, Max 24 characters. Containing letters, spaces and hyphens."></i>
                    <%= text_field_tag("camera-name", @user['camera-name'], "class" => "form-control", "id" => "camera-name", "required" =>"
                    ", "data-validation" => "alphanumeric length", "data-validation-length" => "max24", "maxlength" => "24", "data-validation-allowing" => "-_ ", "data-validation-error-msg" => "Containing letters, spaces and hyphens.") %>
                    <%= label_tag('camera-name', "Camera Friendly Name*") %>
                    <% if field_errors["name"] %>
                    <span class="help-block form-error text-left"><%= field_errors["name"] %></span>
                    <% end %>
                  </div>
                </div>
                <div class="<%= field_errors["vendor"] ? ' has-error' : '' %> col-sm-4 col-md-4">
                  <div class="form-group">
                    <%= label_tag('camera-vendor', "Camera Vendor", class: "control-label") %>
                    <div class="dropdown">
                      <select id="camera-vendor" name="camera-vendor" class="form-control">
                        <option value="">Select Camera Vendor</option>
                      </select>
                    </div>
                    <input type="hidden" id="last-selected-vendor" value="<%= @user['camera-vendor'] %>">
                    <% if field_errors["vendor"] %>
                    <span class="help-block form-error text-left"><%= field_errors["vendor"] %></span>
                    <% end %>
                  </div>
                </div>
                <div id="reveal" class="<%= field_errors["model"] ? ' has-error' : '' %> col-sm-4 col-md-4">
                  <div class="form-group">
                    <%= label_tag('camera-model', "Camera Model", class: "control-label") %>
                    <i class="far fa-question-circle help-icon vendor-help-icon" aria-hidden="true" title="Select 'Default' if you're unsure"></i>
                    <div class="dropdown">
                      <select id="camera-model" name="camera-model" class="form-control camera-model">
                        <option value="">Select Camera Model</option>
                      </select>
                    </div>
                    <input type="hidden" id="last-selected-model" value="<%= @user['camera-model'] %>">
                    <% if field_errors["model"] %>
                    <span class="help-block form-error text-left"><%= field_errors["model"] %></span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='row margin-top-20'>
              <div class='col-sm-12'>
                <div id="unreveal" class="col-sm-4 col-md-4">
                  <div id="ext-ip" class='<%= field_errors["external_host"] ? ' has-error' : '' %>'>
                    <span class="prepend prepend-3">http://</span>
                    <div class="form-group margin-bottom-0">
                      <i class="far fa-question-circle help-icon url-help-icon" aria-hidden="true" title="This should be in the form of 149.5.43.10 or portlarochelle.com."></i>
                      <%= text_field_tag("camera-url", @user['camera-url'], "class" => "form-control", "data-validation" => "custom", "data-validation-regexp" => "^[a-zA-Z0-9._/-]{2,100}$", "data-validation-error-msg" => "This should be in the form of <strong>149.5.43.10</strong> or <strong>portlarochelle.com</strong>. Your IP address is #{@ip}") %>
                      <%= label_tag('camera-url', raw("External <strong>IP</strong> (or URL)*"), class: "float-label") %>
                    </div>
                    <div id="box" class="box">
                      <% if field_errors["external_host"] %>
                        <span class="help-block form-error text-left"><%= field_errors["external_host"] %></span>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class='col-sm-2 col-md-2 <%= field_errors["external_http_port"] ? ' has-error' : '' %>'>
                  <div id="camera-port" class="input-group camera-ext-port">
                    <span class="prepend prepend-1">:</span>
                    <div class="form-group external-port">
                      <%= text_field_tag("port", @user['port'] || 80, "class" => "form-control port-input", "required" => "", "data-validation" => "custom", "data-validation-length" => "max5", "maxlength" => "5", "data-validation-regexp" => "^[0-9]{2,5}$", "data-validation-error-msg" => "The Port should be a 2-5 digit number.") %>
                      <%= label_tag('port', raw("HTTP Port*"), class: "float-label") %>
                      <% if field_errors["external_http_port"] %>
                      <span class="help-block form-error text-left"><%= field_errors["external_http_port"] %></span>
                      <% end %>
                      <div class="port-status"></div>
                      <img src="/assets/refresh.gif" class="refresh-gif refresh-gif-position">
                    </div>
                  </div>
                </div>
                <div class='col-sm-4 col-md-4 <%= field_errors["jpg_url"] ? ' has-error' : '' %>'>
                  <div class="snap-end">
                    <span class="prepend prepend-2">/</span>
                    <div class="form-group">
                      <i class="far fa-question-circle help-icon snapshot-help-icon" aria-hidden="true" title="Include the entire snapshot path after the domain eg.data-externe/webcam/webcam.jpg"></i>
                      <input id="snapshot-readonly" class="form-control snapshot-readonly opacity hide" disabled value="<%= @user['snapshot'] %>"/>
                      <%= text_field_tag("snapshot", @user['snapshot'], "required" => "required", "class" => "form-control", "data-validation" => "alphanumeric", "data-validation-allowing" => "-_/.&?=", "data-validation-error-msg" => "") %>
                      <%= label_tag('snapshot', "Snapshot URL*") %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row margin-top-20">
              <div class='col-sm-12'>
                <div class='<%= field_errors["username"] ? ' has-error' : '' %>'>
                  <div class="col-sm-4 col-md-4">
                    <div class="form-group">
                      <i class="far fa-question-circle help-icon username-help-icon" aria-hidden="true" title="Required if the camera needs authenticating."></i>
                      <%= text_field_tag("camera-username", @user['camera-username'], "class" => "form-control") %>
                      <%= label_tag('camera-username', "Camera Username", class: "float-label") %>
                      <% if field_errors["username"] %>
                      <span class="help-block form-error text-left"><%= field_errors["username"] %></span>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class='<%= field_errors["password"] ? ' has-error' : '' %>'>
                  <div class="col-sm-4 col-md-4">
                    <div class="form-group">
                      <i class="far fa-question-circle help-icon password-help-icon" aria-hidden="true" title="Enter the Password of the camera."></i>
                      <%= text_field_tag("camera-password", @user['camera-password'], class: "form-control") %>
                      <%= label_tag('camera-password', "Camera Password", class: "float-label") %>
                      <% if field_errors["password"] %>
                      <span class="help-block form-error text-left"><%= field_errors["password"] %></span>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class='form-actions col-sm-6 margin-top-20'>
              <div class="form-group">
                <label class="control-label" for="add-button"></label>
                <section class="progress-demo">
                  <button id="add-button" name="add-button" class="btn btn-primary ladda-button" role="button" data-size="xl" data-style="expand-left">
                    Add Camera
                  </button>
                </section>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="media" id="add-test">
              <div class="test-img-holder">
                <img id="testimg" src="" class="text-center testimg-add hide" width="100%">
                <div class="img-holder-text">
                  Fill in your camera details<br> and click below to test the connection
                </div>
              </div>
              <div class="test-snapshot">
                <section class="progress-demo">
                  <a id="test" class="btn btn-primary ladda-button" role="button" data-style="expand-left"><span class="ladda-label">Test Snapshot</span></a>
                </section>
                <div id="test-error"><span></span></div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
  window.initializeAddCamera();
  });
</script>