evercam-dashboard/config/routes.rb
Rails.application.routes.draw do
  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v2/payments' => 'payments#new', as: :new_checkout
  post '/v2/payments' => 'payments#create', as: :new_charge

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v2/cameras'), as: :root
  get '/v2/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras' => 'cameras#index'  # temporary route
  get '/v2/cameras/new' => 'cameras#new', as: :cameras_new
  post '/v2/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v2/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id' => 'cameras#single' # temporary route
  get '/v2/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v2/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v2/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v2/cameras/:id/archives/:archive_id/play' => 'pages#play', as: :play_clip
  get '/v2/cameras/:id/share/request' => 'pages#revoke_request'
  get '/v2/swagger' => "pages#swagger"
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v2/cameras/:id/*subpath' => 'cameras#single'

  get '/v2/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/timelapses' => 'timelapses#index', as: :timelapses_index

  get '/v2/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v2/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v2/users/signup' => 'users#new', as: :signup
  get '/v1/users/signup' => 'users#new' # temporary route
  post '/v2/users/signup' => 'users#create'
  post '/v1/users/signup' => 'users#create' # temporary route
  get '/v2/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v2/users/password-reset' => 'users#password_reset_request'
  get '/v2/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v2/users/password-new' => 'users#password_update'
  get '/confirm' => 'users#confirm'
  get '/v2/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  get '/v2/users/signout' => 'sessions#destroy'
  get '/v1/users/signout' => 'sessions#destroy' # temporary route
  delete '/v2/users/signout' => 'sessions#destroy', as: :signout

  # Removed username from url
  get '/v2/users/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/v2/users/account' => 'users#settings', as: :user_settings
  get '/v2/users/settings', to: redirect("/v2/users/account")
  delete '/v2/users/account' => 'users#delete'
  post '/v2/users/account' => 'users#settings_update'
  put '/v2/users/password/change' => 'users#change_password', as: :user_change_password
  # Removed username from url

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'

  namespace :widgets do
    resources :widget_cameras_add, path: :widget_cameras_add
    get '/cameras/add' => 'widget_cameras_add#widget_add_camera', as: :widget_camera_add
    get '/cameras/public/add' => 'widget_cameras_add#add_public_camera'
    get '/add.camera' => 'widget_cameras_add#add_camera'

    resources :widget_timelapse, path: :widget_timelapse
    get '/timelapse-widget' => 'widget_timelapse#timelapse_js'
  end

  get '/test' => 'cameras#test', as: :test
  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

evercam-dashboard/app/models/evercam_models/user.rb
require 'bcrypt'
class User < Sequel::Model
  include BCrypt
  many_to_one :country
  one_to_many :cameras, key: :owner_id
  one_to_many :grants,
              class: 'AccessToken',
              conditions: Sequel.negate(client_id: nil),
              key: :user_id
  one_to_one  :token,
              class: 'AccessToken',
              conditions: { client_id: nil },
              after_load: proc { |u| u.send(:ensure_token_exists) },
              key: :user_id
  one_to_many :camera_shares

  def self.by_login(login)
    username_query = Sequel.ilike(:username, login)
    email_query = Sequel.ilike(:email, login)
    where(username_query).or(email_query).first
  end

  def fullname
    [firstname, lastname].join(' ')
  end

  def password
    Password.new(values[:password])
  end

  def password=(val)
    values[:password] = Password.create(val, cost: 10)
  end

  def before_save
    values[:encrypted_password] = values[:password]
    super
  end

  def confirmed?
    false == confirmed_at.nil?
  end

  def allow?(token)
    if token
      if token.user == self
        return true
      end
    end
  end

  def validate
    super
    errors.add(:firstname, "is invalid") if (/^[\p{Word}\s,.']+$/ =~ firstname).nil?
    errors.add(:lastname, "is invalid") if (/^[\p{Word}\s,.']+$/ =~ lastname).nil?
    errors.add(:email, "is invalid") if (/^.+@.+\..+$/ =~ email).nil?
  end

  private

  def ensure_token_exists
    self.token ||= AccessToken.new(
      expires_at: Time.at(2**31))
  end
end

evercam-dashboard/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:new, :create, :confirm,
                     :password_reset_request, :password_update, :password_update_form]
  layout "bare-bones", except: [:settings, :delete]
  include SessionsHelper
  include ApplicationHelper
  require "date"

  def new
    if params[:key] && current_user
      sign_out
    end
    unless current_user.nil?
      single_camera_redirection(cameras_index_path)
    end
    @share_request = nil
    get_referral_url()

    if params[:key]
      @share_request = CameraShareRequest.where(
        key: params[:key]
      ).first
      unless @share_request.nil?
        user = User.where(Sequel.ilike(:email, @share_request.email)).first
        unless user.blank?
          flash[:error] = "This signup link has already been used by #{@share_request.email.downcase}, You should either login to your existing account or create a new account."
          redirect_to signin_path
        end
      end
    end
  end

  def create
    user = params[:user]
    begin
      if user.nil?
        raise "No user details specified in request."
      end
      if request.safe_location && Evercam::Config.env == :production
        params[:country] = request.safe_location.country_code.downcase
      end

      get_evercam_api.create_user(
        user['firstname'],
        user['lastname'],
        "",
        user['email'],
        user['password'],
        ENV['WEB_APP_TOKEN'],
        params[:country],
        params[:key],
        session[:referral_url]
      )

      user = User.where(Sequel.ilike(:email, user[:email])).first
      sign_in user
      session[:referral_url] = nil
      update_user_intercom user
      single_camera_redirection(cameras_index_path)
    rescue => error
      if error.kind_of?(Evercam::EvercamError)
        if error.message.eql?("Invalid token.")
          flash[:message] = error.message
        else
          response = instance_eval{(error.message).first}
          if error.try(:status_code).present? && error.status_code.equal?(400)
            assess_field_errors(response)
          else
            flash[:message] = response.last.first
          end
        end
      else
        flash[:message] = "An error occurred creating your account. Please check "\
                            "the details and try again. If the problem persists, "\
                            "contact support."
      end
      Rails.logger.error "Exception caught in create user request.\nCause: #{error}\n" +
          error.backtrace.join("\n")
      render action: "new", user: user
    end
  end

  def confirm
    user = User.by_login(params[:u])
    unless user.nil?
      code = Digest::SHA1.hexdigest(user.username + user.created_at.utc.to_s)
      if params[:c] == code
        user.confirmed_at = Time.now
        user.save
        flash[:notice] = 'Successfully activated your account'
      else
        flash[:notice] = 'Activation code is incorrect'
      end
    end
    redirect_to signin_path
  end

  def settings
    @cameras = load_user_cameras(true, false)
    @countries = Country.all
    @countries.sort_by! { |e| e.name.downcase }
    render layout: "user-account"
  end

  def delete
    begin
      get_evercam_api.delete_user(current_user.email)
      redirect_to good_bye_path
    rescue => error
      Rails.logger.error "Exception caught deleting user.\nCause: #{error}\n" +
                           error.backtrace.join("\n")
      flash[:message] = "An error occurred deleting user. Please try again "\
                      "and, if the problem persists, contact support."
      redirect_to user_settings_path
    end
  end

  def settings_update
    begin
      user_email = current_user.email
      parameters = {}
      parameters[:firstname] = params['user-firstname'] if params.include?('user-firstname')
      parameters[:lastname] = params['user-lastname'] if params.include?('user-lastname')
      parameters[:telegram_username] = params['telegram-username'] if params.include?('telegram-username')
      parameters[:country] = params['country'] if params.include?('country')
      if params.include?('email')
        unless params['email'] == current_user.email
          parameters[:email] = params['email']
          parameters[:username] = params['email']
          user_email = params['email']
        end
      end
      if !parameters.empty?
        old_email = current_user.email
        get_evercam_api.update_user(current_user.username, parameters)
        session[:user] = User.by_login(user_email).email
        update_user_intercom(current_user, old_email)
        refresh_user
      end

      if old_email != current_user.email && send_confirmation_email
        flash[:message] = 'Settings updated successfully and we’ve sent you a confirmation email with instructions.'
      else
        flash[:message] = 'Settings updated successfully'
      end
    rescue => error
      Rails.logger.error "Exception caught in update user request.\nCause: #{error}\n" +
          error.backtrace.join("\n")
      if error.kind_of?(Evercam::EvercamError)
        response = instance_eval{(error.message).first}
        if response[1] && response[1][0]
          flash[:message] = response[1][0]
        else
          flash[:message] = "An error occurred updating your details. Please try "\
          "again and, if the problem persists, contact support."
        end
      else
        flash[:message] = "An error occurred updating your details. Please try "\
                        "again and, if the problem persists, contact support."
      end
    end
    redirect_to user_settings_path
  end

  def change_password
    begin
      user = User.by_login(current_user.email)
    rescue NoMethodError => error
      Rails.logger.error "Error caught fetching user details.\nCause: #{error}\n" + error.backtrace.join("\n")
    end

    if !user.nil? and user.password == params['current-password']
      user.update(password: params['new-password'])
      user.save
      flash[:message] = 'Password updated successfully'
    else
      flash[:message] = 'Invalid Current Password'
    end
    redirect_to user_settings_path
  end

  def password_reset_request
    get_referral_url()
    email = params[:email].downcase if params[:email]
    unless email.nil?
      user = User.by_login(email)

      if user
        t = Time.now
        if user.reset_token.present? and user.token_expires_at.present? and user.token_expires_at > t
          expires = user.token_expires_at
          token = user.reset_token
        else
          expires = t + 24.hour
          token = SecureRandom.hex(16)
        end

        user.update(reset_token: token, token_expires_at: expires)

        UserMailer.password_reset(email, user, token).deliver_now
        flash.now[:message] = "We’ve sent you an email with instructions for changing your password."
      else
        flash.now[:message] = "Email address not found."
      end
    end
  end

  def password_update_form
    username = params[:u]
    user = User.by_login(username)
    if user.nil? or user.token_expires_at.blank? or user.token_expires_at < Time.now
      @expired = true
    else
      @expired = false
    end
    render "password_update"
  end

  def password_update
    token = params[:token]
    username = params[:username]
    user = User.by_login(username)
    if user.nil? or token != user.reset_token or user.token_expires_at < Time.now
      flash[:message] = 'Invalid username or token'
    else
      user.update(reset_token: '', token_expires_at: Time.now)
      user.password = params[:password]
      user.save
      sign_in user
      redirect_to cameras_index_path, message: 'Your password has been changed'
    end
  end

  def resend_confirmation_email
    result = send_confirmation_email
    unless result
      flash[:message] = 'We’ve sent you a confirmation email with instructions.'
    else
      flash[:message] = t("errors.user_not_found_error")
    end
    redirect_to user_settings_path
  end

  private

  def send_confirmation_email
    user = User.where(Sequel.ilike(:email, current_user.email)).first
    unless user.nil?
      code = Digest::SHA1.hexdigest(user.username + user.created_at.utc.to_s)
      UserMailer.resend_confirmation_email(user, code).deliver_now
      true
    else
      false
    end
  end

  def assess_field_errors(error)
    field_errors = {}
    field_errors[error.first] = error.last.first
    flash[:field_errors] = field_errors
  end
end

evercam-dashboard/app/helpers/users_helper.rb
module UsersHelper
end

evercam-dashboard/app/views/users/settings/_account_tab.html.erb
<div id="user-settings">
  <div class="user-settings-portal col-sm-6 col-md-4 col-lg-4">
    <div class="profile">
      <%= image_tag avatar_url(current_user.email), class: 'gravatar pull-left' %>
      <div class="username">
        <span class="grey">Email </span><span> <%= current_user.email -%></span>
      </div>
      <p class="small grey">Manage your avatar with <a href="https://en.gravatar.com/" target="_blank">Gravatar</a> </p>
    </div>
    <div class="portlet-body form">
      <form id="userProfile" role="form" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <div class="form-group">
          <input data-validation="email" type="text" value="<%= current_user.email -%>" class="form-control" id="email" name="email" required>
          <i class="minus-margin-top-25 float-right margin-right-10 far fa-envelope font-16 icon-color"></i>
          <span class="form-highlight"></span>
          <span class="form-bar"></span>
          <label class="float-label" for="email">Email</label>
        </div>
        <div class="form-group">
          <input data-validation-error-msg="Cannot be blank" data-validation="length" data-validation-length="min1" type="text" value="<%= current_user.firstname -%>" class="form-control" id="user-firstname" name="user-firstname" required>
          <span class="form-highlight"></span>
          <span class="form-bar"></span>
          <label class="float-label" for="user-firstname">First Name</label>
        </div>
        <div class="form-group">
          <input data-validation-error-msg="Cannot be blank" data-validation="length" data-validation-length="min1" type="text" value="<%= current_user.lastname -%>" class="form-control" id="user-lastname" name="user-lastname" required>
          <span class="form-highlight"></span>
          <span class="form-bar"></span>
          <label class="float-label" for="user-lastname">Last Name</label>
        </div>
        <div class="form-group">
          <input data-validation="length" data-validation-length="min0" type="text" value="<%= current_user.telegram_username -%>" class="form-control" id="telegram-username" name="telegram-username">
          <i class="minus-margin-top-25 float-right margin-right-10 fab fa-telegram font-16 icon-color"></i>
          <span class="form-highlight"></span>
          <span class="form-bar"></span>
          <label class="float-label" for="user-lastname">Telegram Username</label>
        </div>
        <div class="form-group">
          <label class="grey" for="country">Country</label>
          <select id="country" name="country" class="form-control">
            <% if current_user.country.blank? %>
              <option value="">Not Specified</option>
            <% end %>
            <% @countries.each do |c| %>
              <option value="<%= c.iso3166_a2 -%>" <%= 'selected="selected"' if c == current_user.country %>>
                <%= c.name -%>
              </option>
            <% end %>
          </select>
        </div>
        <div class="margin-top-40 row">
          <div class="col-md-12">
          <input type="submit" class="btn blue" value="Update" name="Save"/>
          </div>
        </div>
      </form>
      <% unless current_user.confirmed_at %>
        <div class="alert alert-info alert-dismissible fade in margin-top-40" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
              <span>
                It looks like your account has not been verified yet.
                <%= link_to 'Resend verification email.', user_email_resend_path, class: 'resend-email' %>
              </span>
        </div>
      <% end %>
    </div>
    <div class="table-responsive table-borderless table-fixed col-lg-6 col-md-6 col-sm-12 no-padding margin-top-20">
      <table class="table">
        <tr>
          <td class="online-offline-toggle padding-left-0">
            <strong>Hide Offline Cameras</strong>
          </td>
          <td>
            <div id="siderbar">
              <label class="label toggle title">
                <input type="checkbox" class="toggle_input" id="offline-btn"/>
                <div class="toggle-control"></div>
              </label>
            </div>
          </td>
        </tr>
        <tr>
          <td class="padding-left-0">
            <p class="delete" data-toggle="modal" data-target="#delete-account">Delete your account</p>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

<form role="form" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
<div class="modal fade" id="delete-account" tabindex="-1" role="dialog" aria-labelledby="delete-account" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close margin-top-minus5" data-dismiss="modal" aria-hidden="true"><i class="fas fa-times"></i></button>
        <h5>Delete your account (<%= current_user.email -%>) </h5>
      </div>
      <div class="modal-body">
        <div class="">
          <% @cameras.each do |camera| %>
            <% if camera['owned'] %>
              <p class="text-left">You must confirm you would like to delete the cameras you own or you can transfer ownership before deleting your account. <br>Check the box to confirm you would like to delete the camera:</p>
              <div class="camera-row">
                <div class="form-group checkbox">
                  <input id="chk-camera-<%= camera['id'] %>" class="camera-delete" type="checkbox" value="<%= camera['id'] %>"> <label for="chk-camera-<%= camera['id'] %>" class="camera-row-label"><%= camera['name'] %></label>
                  <label class="transfer-span"><%= link_to 'Transfer camera', "#{cameras_single_path(camera['id'])}/shares/transfer", class: 'transfer-link' %></label>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <p class="text-left margin-top-20">Type 'Delete' to confirm you would like delete your account and any cameras you currently own.</p>
        <input data-validation-error-msg="Cannot be blank" required="true" type="text" class="form-control" id="delete-camera" name="delete-camera" required>
      </div>
      <div class="modal-footer">
        <input type="hidden" name="_method" value="delete"/>
        <input type="submit" id="close-account" name="close-account" class="btn btn-danger pull-left" value="Delete Account">
      </div>
    </div>
  </div>
</div>
</form>

evercam-dashboard/app/views/users/settings/_password_tab.html.erb
<div id="user-settings">
  <div class="user-settings-portal col-md-4 col-lg-4">
    <div class="portlet-body form">
      <form id="userPassword" role="form" method="post" action="<%= user_change_password_path %>">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <div class="form-group">
          <input data-validation="current-password" data-validation-error-msg="Cannot be blank" required="true" type="password" class="form-control" id="current-password" name="current-password" required>
          <span class="form-highlight"></span>
          <span class="form-bar"></span>
          <label class="float-label" for="current-password">Current Password</label>
        </div>
        <div class="form-group">
          <input data-validation="new-password" required="true" type="password" class="form-control" id="new-password" name="new-password" required>
          <span class="form-highlight"></span>
          <span class="form-bar"></span>
          <label class="float-label" for="new-password">New Password</label>
        </div>
        <div class="form-group">
          <input data-validation="password_again" required="true" type="password" class="form-control" id="password_again" name="password_again" required>
          <span class="form-highlight"></span>
          <span class="form-bar"></span>
          <label class="float-label" for="password_again">Confirm Password</label>
          <span id="wrong-confirm-password" class="error-msg-color">Please enter the same password as above.</span>
        </div>
        <div class="margin-top-20">
          <div class="row">
            <div class="col-md-12">
              <input type="hidden" name="_method" value="put"/>
              <input type="submit" id="change-password" class="btn blue" value="Change Password" name="change-password"/>
            </div>
          </div>
          <div class="col-md-3"></div>
        </div>
      </form>
    </div>
  </div>
</div>

evercam-dashboard/app/views/users/settings/_user_activities_tab.html.erb
<div id="logs-filter" class="filter">
  <div class="row dates margin-top-10">
    <div class="col-sm-1 min-width-114 set-margin padding-right-left-10"><h5>Filter by:</h5></div>
    <div class="col-sm-6 min-width200">
      From: <input id="datetimepicker_from" class="datetimepicker" type="text" value="" placeholder="From Date">
      To: <input id="datetimepicker_to" class="datetimepicker to-time" type="text" value="" placeholder="To Date">
      <button id="search-logs" class="btn btn-primary btn-setting filter-button">Filter</button>
    </div>
  </div>
</div>
<div class="container-margin">
  <table id="user-activity" class="table table-striped table-bordered cell-border display compact responsive">
    <thead>
      <th data-priority="5" class="landscape">Browser</th>
      <th data-priority="1" class="all">IP address</th>
      <th data-priority="4" class="landscape">Country</th>
      <th data-priority="3" class="all">Date &amp; Time</th>
      <th data-priority="2" class="all">Event</th>
    </thead>
    <tbody class="font-12"></tbody>
  </table>
</div>