evercam-dashboard/config/routes.rb
Rails.application.routes.draw do
  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v2/payments' => 'payments#new', as: :new_checkout
  post '/v2/payments' => 'payments#create', as: :new_charge

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v2/cameras'), as: :root
  get '/v2/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras' => 'cameras#index'  # temporary route
  get '/v2/cameras/new' => 'cameras#new', as: :cameras_new
  post '/v2/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v2/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id' => 'cameras#single' # temporary route
  get '/v2/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v2/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v2/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v2/cameras/:id/archives/:archive_id/play' => 'pages#play', as: :play_clip
  get '/v2/cameras/:id/share/request' => 'pages#revoke_request'
  get '/v2/swagger' => "pages#swagger"
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v2/cameras/:id/*subpath' => 'cameras#single'

  get '/v2/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/timelapses' => 'timelapses#index', as: :timelapses_index

  get '/v2/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v2/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v2/users/signup' => 'users#new', as: :signup
  get '/v1/users/signup' => 'users#new' # temporary route
  post '/v2/users/signup' => 'users#create'
  post '/v1/users/signup' => 'users#create' # temporary route
  get '/v2/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v2/users/password-reset' => 'users#password_reset_request'
  get '/v2/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v2/users/password-new' => 'users#password_update'
  get '/confirm' => 'users#confirm'
  get '/v2/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  get '/v2/users/signout' => 'sessions#destroy'
  get '/v1/users/signout' => 'sessions#destroy' # temporary route
  delete '/v2/users/signout' => 'sessions#destroy', as: :signout

  # Removed username from url
  get '/v2/users/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/v2/users/account' => 'users#settings', as: :user_settings
  get '/v2/users/settings', to: redirect("/v2/users/account")
  delete '/v2/users/account' => 'users#delete'
  post '/v2/users/account' => 'users#settings_update'
  put '/v2/users/password/change' => 'users#change_password', as: :user_change_password
  # Removed username from url

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'

  namespace :widgets do
    resources :widget_cameras_add, path: :widget_cameras_add
    get '/cameras/add' => 'widget_cameras_add#widget_add_camera', as: :widget_camera_add
    get '/cameras/public/add' => 'widget_cameras_add#add_public_camera'
    get '/add.camera' => 'widget_cameras_add#add_camera'

    resources :widget_timelapse, path: :widget_timelapse
    get '/timelapse-widget' => 'widget_timelapse#timelapse_js'
  end

  get '/test' => 'cameras#test', as: :test
  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

evercam-dashboard/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:pay, :make_payment, :thank]
  layout "user-account"
  include SessionsHelper
  include ApplicationHelper
  require "stripe"

  def pay
    render layout: "bare-bones"
  end

  def thank
    render layout: "bare-bones"
  end

  def make_payment
    begin
      token = create_token(params)
      response = make_custom_payment(params, token)
      redirect_to thank_payment_path
    rescue => error
      flash[:error] = error.message
      redirect_to pay_path
    end
  end

  private

  def create_token(params)
    Stripe::Token.create(
      :card => {
        :number => params["card-number"],
        :exp_month => params["expiry-month"],
        :exp_year => params["expiry-year"],
        :cvc => params["card-cvc"]
      },
    )
  end

  def make_custom_payment(params, token)
    amount = params[:amount].to_f * 100
    Stripe::Charge.create(
      :amount => amount.to_i,
      :currency => "eur",
      :source => token.id,
      :description => "Charge for #{params[:email]}"
    )
  end
end

evercam-dashboard/app/views/payments/pay.html.erb
<section id="make-payment-section">
  <div class="container section">
    <div id="signin" class="col-md-12 text-center">
      <div class="bb-alert alert alert-danger" style="display:none;">
        <span></span>
      </div>
      <div class="branding margin-bottom-50">
        <%= link_to root_path, class: 'sign-in-logo' do %>
          <%= image_tag("evercam_logo.png", :class => "svg-logo", alt: "Evercam.io") %>
        <% end %>
      </div>
    </div>

    <div id="sign-in" class="make-payment col-md-6 col-md-offset-3">
      <h3 class="text-center">PAY WITH CARD</h3>
      <form action="<%= make_payment_path %>" method="post" id="example-form">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <div class="col-md-10 col-md-offset-1">
          <label for="email">E-mail Address</label>
          <div class="input-icon right">
            <i class="fa fa-envelope"></i>
            <input type="text" name="email" id="email" class="required" />
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <label for="reference">Invoive Or Reference Number</label>
          <div class="input-icon right">
            <i class="fa fa-euroa">#</i>
            <input type="text" name="reference" class="required" />
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <label for="amount">Payment Amount</label>
          <div class="input-icon right">
            <i class="fa fa-euro">€</i>
            <input type="text" name="amount" id="amount" class="required"/>
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <div class="col-md-6 adjust-padding-col1">
            <div class="row1">
              <label for="name" class="stripeLabel">Card Holder's Name</label>
              <input type="text" name="name" id="name" class="required" />
            </div>
          </div>
          <div class="col-md-6 adjust-padding-col2">
            <div class="row1">
              <label>Card Number</label>
              <input id="card-number" name="card-number" type="text" maxlength="20" autocomplete="off" class="card-number stripe-sensitive required" />
            </div>
          </div>
        </div>

        <div class="col-md-10 col-md-offset-1">
          <ul class="cards unstyled">
            <li>
              <span class="card amex" title="American Express">AMEX</span>
            </li>
            <li>
              <span class="card master" title="Mastercard">MC</span>
            </li>
            <li>
              <span class="card visa" title="Visa">VISA</span>
            </li>
            <li>
              <span class="card stripe" title="stripe">stripe</span>
            </li>
          </ul>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <div class="col-md-4 adjust-padding-col1">
            <label>Card CVC</label>
            <input name="card-cvc" id="card-cvc" type="text" maxlength="4" autocomplete="off" class="card-cvc stripe-sensitive required" />
          </div>
          <div class="col-md-4 adjust-padding-col1">
            <label>Month</label>
            <select name="expiry-month" id="expiry-month" class="form-control card-expiry-month expiry-drop-down">
            </select>
            <script type="text/javascript">
              var select = $(".card-expiry-month"),
                month = new Date().getMonth() + 1;
              for (var i = 1; i <= 12; i++) {
                select.append($("<option value='"+i+"' "+(month === i ? "selected" : "")+">"+i+"</option>"))
              }
            </script>
          </div>
          <div class="col-md-4 adjust-padding-col2">
            <label>Year</label>
            <select name="expiry-year" id="expiry-year" class=" form-control card-expiry-year expiry-drop-down"></select>
            <script type="text/javascript">
              var select = $(".card-expiry-year"),
                year = new Date().getFullYear();
              for (var i = 0; i < 12; i++) {
                select.append($("<option value='"+(i + year)+"' "+(i === 0 ? "selected" : "")+">"+(i + year)+"</option>"))
              }
            </script>
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1 margin-top-20">
          <button class="btn btn-large btn-primary col-lg-10 col-lg-offset-1" type="submit" name="submit-button" id="submit-button">Make Payment</button>
          <span class="payment-errors"></span>
        </div>
      </form>
    </div>

    <div class="grey col-md-4 col-md-offset-4 row text-center margin-top-20">
      <p> <%= link_to "Sign in", signin_path %></p>
    </div>
  </div>
</section>

<script>
  window.initializePay();
  Notification.init(".bb-alert");
  <% if flash[:error] %>
  Notification.show('<%= flash[:error] %>');
  <% end %>
</script>

evercam-dashboard/app/views/payments/thank.html.erb
<section id="make-payment-section">
  <div class="container section">
    <div id="signin" class="col-md-12 text-center">
      <div class="bb-alert alert alert-danger" style="display:none;">
        <span></span>
      </div>
      <div class="branding margin-bottom-50">
        <%= link_to root_path, class: 'sign-in-logo' do %>
          <%= image_tag("evercam_logo.png", :class => "svg-logo", alt: "Evercam.io") %>
        <% end %>
      </div>
    </div>

    <div id="sign-in" class="make-payment col-md-6 col-md-offset-3">
      <div class="col-md-10 col-md-offset-1 text-center">
        Payment completed. Thank You
      </div>
    </div>

    <div class="grey col-md-4 col-md-offset-4 row text-center margin-top-20">
      <p> <%= link_to "Sign in", signin_path %></p>
    </div>
  </div>
</section>